- name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy Artifact
        uses: actions/deploy-pages@v4 # 👈 Missing an ending newline character